### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by RoseSecurity** [Kleptocratic/Roku-Hacking#1]
![Roku](https://user-images.githubusercontent.com/72598486/133314573-0f0ebc16-9d51-4c1f-b2ad-1c7e15851214.png)

**Comment by mathieu-aubin** [comment]
this is what the image looks like on a dark backgound...

![cAFYdhKl](https://github.com/RoseSecurity/Abusing-Roku-APIs/assets/15820228/9abeca24-a81b-477e-a0db-dab62b6026fb)
