### ISSUE TITLE
roku mac addresses

### ISSUE THREAD

**Issue by mathieu-aubin** [Kleptocratic/Roku-Hacking#3]
here's what i got from `arp-scan --localnet`

`192.168.0.3		8c:49:62:47:e6:ed	Roku, Inc`

seems like this wasn't part of the mac you suggested so i figured i would add here without making a whole commit and potentially disturbing everything

**Comment by RoseSecurity** [comment]
> here's what i got from `arp-scan --localnet`
> 
> 
> 
> `192.168.0.3		8c:49:62:47:e6:ed	Roku, Inc`
> 
> 
> 
> seems like this wasn't part of the mac you suggested so i figured i would add here without making a whole commit and potentially disturbing everything
> 
> 

Thank you for opening this issue! I believe `8c:49:62` is a part of the list of MACs provided in the README, but if it isn't, feel free to add it. I really like the idea of doing an ARP scan to identify this. I should probably update the nmap scan to depict a UDP scan so the correct ports are evident.

**Comment by mathieu-aubin** [comment]
you are right. i got this crossed eyed somewhat - thanks for straightening my crooked ways!

Oh and yes, `arp-scan` is very fast too.

**Comment by mathieu-aubin** [comment]
from `cat /usr/share/arp-scan/ieee-oui.txt | grep -i roku |sort` i was able to get 22 MAC. I think you list 20? Anyways... Enjoy yourself and thank you!

```
000D4B	Roku, Inc.
080581	Roku, Inc.
105932	Roku, Inc
20EFBD	Roku, Inc
7C67AB	Roku, Inc
84EAED	Roku, Inc
88DEA9	Roku, Inc.
8C4962	Roku, Inc
A8B57C	Roku, Inc
AC3A7A	Roku, Inc.
ACAE19	Roku, Inc
B0A737	Roku, Inc.
B0EE7B	Roku, Inc
B83E59	Roku, Inc.
B8A175	Roku, Inc.
BCD7D4	Roku, Inc
C83A6B	Roku, Inc
CC6DA0	Roku, Inc.
D04D2C	Roku, Inc.
D4E22F	Roku, Inc
D83134	Roku, Inc
DC3A5E	Roku, Inc.
```

**Comment by RoseSecurity** [comment]
@mathieu-aubin Thank you for bringing this up! Just updated it! https://github.com/RoseSecurity/Abusing-Roku-APIs/commit/82edc3a13d884f12ab6673f52959e5a7047d04de
